### ISSUE TITLE
Server returns response with empty data when we make click on submit button first time after deploy

### ISSUE THREAD

**Issue by olegvn88** [radanalyticsio/jiminy-html-server#21]
Server returns response with empty data when we make click on submit button first time after deploy.

**Steps to reproduce:**
1. Goto main page of Project Jiminy Recommendation Engine and input the value 10 to "Select User" field
2. Click on "Submit" button one time.

**Expected result:**
Recommended products for user are displayed.

**Actual result:**
Recommended products for user is empty.

**Workaround:** Click on "Submit" button again and recommended products for user are displayed.

**Note:** The issue reproduced only one time after deploy

Here you can find example of request and response:
Case1:
Request : GET http://html-server-olnester-testsuite.10.19.47.76.nip.io/api/predictor/10
Response "{"status":"OK","columns":[{"data":"description","title":"Description"},{"data":"rating","title":"Rating"}],"dataSet":[]}"
Case2: 
Request : GET http://html-server-olnester-testsuite.10.19.47.76.nip.io/api/predictor/10
Response: "status | OK
-- | --
columns | […]
0 | {…}
data | description
title | Description
1 | {…}
data | rating
title | Rating
dataSet | […]
0 | {…}
id | 7234
description | Strada, La (1954)
rating | 5
1 | {…}
id | 8014
description | Spring, Summer, Fall, Winter... and Spring (Bom yeoreum gaeul gyeoul geurigo bom) (2003)
rating | 5
2 | {…}
id | 8933
description | Decline of the American Empire, The (Déclin de l'empire américain, Le) (1986)
rating | 5
3 | {…}
id | 4278
description | Triumph of the Will (Triumph des Willens) (1934)
rating | 5
4 | {…}
id | 7460
description | Coffee and Cigarettes (2003)
rating | 5"
![case1](https://user-images.githubusercontent.com/20247663/42927564-86256046-8b3d-11e8-8e7a-13a2177bd832.png)
![case2](https://user-images.githubusercontent.com/20247663/42927565-8640c890-8b3d-11e8-9368-25798bf1d7cb.png)

**Comment by olegvn88** [comment]
@sophwats I've added the screenshots. I guess it should help to find solution.

**Comment by sophwats** [comment]
Thanks @olegvn88

**Comment by erikerlandson** [comment]
I'd suggest trying a readiness probe that tests for a non-empty return value from the REST call

**Comment by erikerlandson** [comment]
I had suggested readiness probe, but that probably isn't going to fix the problem. The jiminy-html-server needs some new logic to detect when it isn't getting a response from its queries and throw up a warning dialog or some such

**Comment by sophwats** [comment]
We have identified the problem, and are going to add a fix so that the front end will give a warning when it gets zero data back from the html-server.

**Comment by elmiko** [comment]
hey @olegvn88 , i added some warning notifications for when the server is slow in responding or if it responds with no data.

please checkout #22 to see if it will work. i don't there there is anything we can do for a situation where the html-server is running but the predictor is slow to return data or it has failed. this will at least alert the user that there is an issue with the data.

**Comment by olegvn88** [comment]
Hey @elmiko @sophwats . I've checked this change, but any alert is not observed (. We have still  the same situation, response returns just empty data.

**Comment by elmiko** [comment]
this has been fixed to give a warning if the data is empty on return, it also now has errors for bad connections.

i am going to close this issue, i think there are a couple features we could add for detecting users who are out of range and perhaps improving the UI when the front end is waiting for a reponse but those should be new issues.
